export const siteConfig = {
  defaultLocale: "en",
  locales: [
    { code: "en", label: "English" },
    { code: "kn", label: "ಕನ್ನಡ" },
  ],
  text: {
    en: {
      documentTitle: "Digital Library | Shri Shiroor Matha",
      siteName: "Shri Shiroor Matha",
      pageTitle: "Digital Library",
      heroKicker: "Kannada devotional literature",
      heroTitle: "Search. Read. Experience.",
      skipLink: "Skip to library content",
      tabsLabel: "Library collections",
      searchHeading: "Search the collection",
      searchDefaultDescription: "Find literature by title, author, ankita, or keyword.",
      searchLabel: "Search library",
      searchPlaceholder: "Search title, author, ankita…",
      libraryKicker: "Library",
      browseHeading: "All works",
      resultSingular: "result",
      resultPlural: "results",
      showingResults: "Showing {shown} of {total} works",
      showAll: "Show all {total} works",
      showLess: "Show fewer works",
      collapseResults: "Collapse",
      expandResults: "Expand",
      noResults: "No matching literature was found.",
      selectedLiterature: "Selected literature",
      readingLabel: "Reading",
      backToResults: "Back to results",
      loading: "Loading literature…",
      unknownAuthor: "Unknown author",
      contentLoadError: "This literature could not be loaded. Please try again.",
      catalogLoadError: "The collection could not be loaded. Please try again.",
      unavailableTitle: "More literature is coming soon",
      unavailableDescription: "This collection is ready for content and will appear here after the next library build.",
      libraryLoadErrorTitle: "The library could not be loaded",
      libraryLoadErrorDescription: "Run the content build and refresh this page.",
      footerTitle: "Dasa Sahitya collection",
      footer: "Preserving words across generations.",
      languageLabel: "Language",
      textSourceLabel: "Text source",
      actualTextOption: "Actual texts",
      generatedTextOption: "Generated placeholders",
    },
    kn: {
      documentTitle: "ಡಿಜಿಟಲ್ ಗ್ರಂಥಾಲಯ | ಶ್ರೀ ಶಿರೂರು ಮಠ",
      siteName: "ಶ್ರೀ ಶಿರೂರು ಮಠ",
      pageTitle: "ಡಿಜಿಟಲ್ ಗ್ರಂಥಾಲಯ",
      heroKicker: "ಕನ್ನಡ ಭಕ್ತಿ ಸಾಹಿತ್ಯ",
      heroTitle: "ಹುಡುಕಿ. ಓದಿ. ಅನುಭವಿಸಿ.",
      skipLink: "ಗ್ರಂಥಾಲಯದ ವಿಷಯಕ್ಕೆ ತೆರಳಿ",
      tabsLabel: "ಗ್ರಂಥಾಲಯ ಸಂಗ್ರಹಗಳು",
      searchHeading: "ಸಂಗ್ರಹದಲ್ಲಿ ಹುಡುಕಿ",
      searchDefaultDescription: "ಶೀರ್ಷಿಕೆ, ಕೃತಿಕಾರರು, ಅಂಕಿತ ಅಥವಾ ಮುಖ್ಯಪದದ ಮೂಲಕ ಸಾಹಿತ್ಯವನ್ನು ಹುಡುಕಿ.",
      searchLabel: "ಗ್ರಂಥಾಲಯದಲ್ಲಿ ಹುಡುಕಿ",
      searchPlaceholder: "ಶೀರ್ಷಿಕೆ, ಕೃತಿಕಾರರು, ಅಂಕಿತ ಹುಡುಕಿ…",
      libraryKicker: "ಗ್ರಂಥಾಲಯ",
      browseHeading: "ಎಲ್ಲಾ ಕೃತಿಗಳು",
      resultSingular: "ಫಲಿತಾಂಶ",
      resultPlural: "ಫಲಿತಾಂಶಗಳು",
      showingResults: "{total} ಕೃತಿಗಳಲ್ಲಿ {shown} ತೋರಿಸಲಾಗುತ್ತಿದೆ",
      showAll: "ಎಲ್ಲಾ {total} ಕೃತಿಗಳನ್ನು ತೋರಿಸಿ",
      showLess: "ಕಡಿಮೆ ಕೃತಿಗಳನ್ನು ತೋರಿಸಿ",
      collapseResults: "ಮುಚ್ಚಿ",
      expandResults: "ತೆರೆಯಿರಿ",
      noResults: "ಹೊಂದಾಣಿಕೆಯಾಗುವ ಸಾಹಿತ್ಯ ಕಂಡುಬಂದಿಲ್ಲ.",
      selectedLiterature: "ಆಯ್ಕೆ ಮಾಡಿದ ಸಾಹಿತ್ಯ",
      readingLabel: "ಓದುತ್ತಿರುವುದು",
      backToResults: "ಫಲಿತಾಂಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
      loading: "ಸಾಹಿತ್ಯ ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
      unknownAuthor: "ಅಜ್ಞಾತ ಕೃತಿಕಾರರು",
      contentLoadError: "ಈ ಸಾಹಿತ್ಯವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
      catalogLoadError: "ಸಂಗ್ರಹವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
      unavailableTitle: "ಹೆಚ್ಚಿನ ಸಾಹಿತ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಾಗಲಿದೆ",
      unavailableDescription: "ಈ ಸಂಗ್ರಹವು ವಿಷಯಕ್ಕೆ ಸಿದ್ಧವಾಗಿದೆ ಮತ್ತು ಮುಂದಿನ ಗ್ರಂಥಾಲಯ ನಿರ್ಮಾಣದ ನಂತರ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
      libraryLoadErrorTitle: "ಗ್ರಂಥಾಲಯವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
      libraryLoadErrorDescription: "ವಿಷಯ ನಿರ್ಮಾಣವನ್ನು ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಪುಟವನ್ನು ಮರುಲೋಡ್ ಮಾಡಿ.",
      footerTitle: "ದಾಸ ಸಾಹಿತ್ಯ ಸಂಗ್ರಹ",
      footer: "ಪದಗಳನ್ನು ಪೀಳಿಗೆಯಿಂದ ಪೀಳಿಗೆಗೆ ಸಂರಕ್ಷಿಸಲಾಗುತ್ತಿದೆ.",
      languageLabel: "ಭಾಷೆ",
      textSourceLabel: "ಪಠ್ಯದ ಮೂಲ",
      actualTextOption: "ನೈಜ ಪಠ್ಯಗಳು",
      generatedTextOption: "ರಚಿಸಿದ ಮಾದರಿ ಪಠ್ಯಗಳು",
    },
  },
};