#!/usr/bin/env node
// Reads content/en.yml + content/kn.yml, validates that both locales share
// the same structural shape (same keys, same ids, same hrefs/dates/icons —
// only human-readable text is allowed to differ), then emits
// src/generated/content.ts. Run via `npm run predev` / `npm run prebuild`,
// or manually via `npm run content:build`.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { load as loadYamlDoc } from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const CONTENT_DIR = resolve(root, "content");
const OUT_DIR = resolve(root, "src", "generated");
const OUT_FILE = resolve(OUT_DIR, "content.ts");

// Fields that carry structural meaning (routing, scheduling, asset keys) and
// must be byte-identical between locales. Anything not listed here is
// treated as translatable text and is allowed to differ.
const STRUCTURAL_KEYS = new Set([
  "href",
  "id",
  "icon",
  "image",
  "bg",
  "portrait",
  "order",
  "pinned_date",
  "launch_date",
  "end_date",
  "valid_for_date",
]);

const CAROUSEL_MIN_ITEMS = {
  "home.carousel1.items": 5,
};

function loadYaml(locale) {
  const filePath = resolve(CONTENT_DIR, `${locale}.yml`);
  const raw = readFileSync(filePath, "utf8");
  return loadYamlDoc(raw);
}

const errors = [];

function pathStr(pathParts) {
  return pathParts.join(".");
}

function validateParity(en, kn, pathParts) {
  const path = pathStr(pathParts);

  if (Array.isArray(en) || Array.isArray(kn)) {
    if (!Array.isArray(en) || !Array.isArray(kn)) {
      errors.push(`${path}: type mismatch (array vs non-array) between en/kn`);
      return;
    }
    if (en.length !== kn.length) {
      errors.push(
        `${path}: item count mismatch — en has ${en.length}, kn has ${kn.length}`
      );
      return;
    }
    en.forEach((enItem, i) => validateParity(enItem, kn[i], [...pathParts, String(i)]));
    return;
  }

  if (en && typeof en === "object") {
    if (!kn || typeof kn !== "object") {
      errors.push(`${path}: type mismatch (object vs non-object) between en/kn`);
      return;
    }
    const enKeys = Object.keys(en).sort();
    const knKeys = Object.keys(kn).sort();
    if (enKeys.join(",") !== knKeys.join(",")) {
      errors.push(
        `${path}: key mismatch — en=[${enKeys}] kn=[${knKeys}]`
      );
    }
    for (const key of enKeys) {
      if (!(key in kn)) continue;
      if (STRUCTURAL_KEYS.has(key) && en[key] !== kn[key]) {
        errors.push(
          `${path}.${key}: structural field differs between locales — en="${en[key]}" kn="${kn[key]}"`
        );
        continue;
      }
      validateParity(en[key], kn[key], [...pathParts, key]);
    }
  }
}

function validateMinItems(en, kn) {
  for (const [path, min] of Object.entries(CAROUSEL_MIN_ITEMS)) {
    const parts = path.split(".");
    let enNode = en;
    let knNode = kn;
    for (const p of parts) {
      enNode = enNode?.[p];
      knNode = knNode?.[p];
    }
    if (!Array.isArray(enNode) || enNode.length < min) {
      errors.push(`${path}: en must have at least ${min} items (has ${enNode?.length ?? 0})`);
    }
    if (!Array.isArray(knNode) || knNode.length < min) {
      errors.push(`${path}: kn must have at least ${min} items (has ${knNode?.length ?? 0})`);
    }
  }
}

function main() {
  const en = loadYaml("en");
  const kn = loadYaml("kn");

  validateParity(en, kn, []);
  validateMinItems(en, kn);

  if (errors.length > 0) {
    console.error("\ncontent validation failed:\n");
    for (const e of errors) console.error(`  - ${e}`);
    console.error(`\n${errors.length} error(s). Fix content/en.yml / content/kn.yml and retry.\n`);
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });

  const banner = `// AUTO-GENERATED by scripts/generate-content.mjs — do not hand-edit.\n// Source: content/en.yml, content/kn.yml\n`;
  const body =
    `import type { ContentShape } from "@/lib/content-types";\n\n` +
    `export const content: { en: ContentShape; kn: ContentShape } = ${JSON.stringify(
      { en, kn },
      null,
      2
    )} as const;\n`;

  writeFileSync(OUT_FILE, banner + body, "utf8");
  console.log(`content generated: ${OUT_FILE.replace(root, ".")}`);
}

main();
